-- Migration: Add campaign strategy fields
-- Run this in Supabase SQL editor

ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS strategy_type TEXT,
  ADD COLUMN IF NOT EXISTS campaign_structure JSONB,
  ADD COLUMN IF NOT EXISTS estimated_results JSONB,
  ADD COLUMN IF NOT EXISTS meta_campaign_id TEXT,
  ADD COLUMN IF NOT EXISTS meta_status TEXT;

-- Index for filtering by strategy type
CREATE INDEX IF NOT EXISTS idx_campaigns_strategy_type ON campaigns(strategy_type);
CREATE INDEX IF NOT EXISTS idx_campaigns_meta_campaign_id ON campaigns(meta_campaign_id);

-- Comment the columns
COMMENT ON COLUMN campaigns.strategy_type IS 'TOFU | MOFU | BOFU — funnel stage selected by user';
COMMENT ON COLUMN campaigns.campaign_structure IS 'Full Meta campaign structure: ad sets + ads generated by AI';
COMMENT ON COLUMN campaigns.estimated_results IS 'AI-estimated daily reach, clicks, conversions, CPM, CPA, ROAS';
COMMENT ON COLUMN campaigns.meta_campaign_id IS 'Meta Ads campaign ID after publishing';
COMMENT ON COLUMN campaigns.meta_status IS 'Meta campaign status: ACTIVE | PAUSED | DELETED | etc';
